---
abstract: 'Schema generator by Files for Mojolicious'
author:
  - 'Lucas Tiago de Moraes <lucastiagodemoraes@gmail.com>'
build_requires:
  Cwd: '0'
  ExtUtils::MakeMaker: '0'
  GraphQL::Schema: '0'
  Mojo::Base: '0'
  Mojo::Util: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.44, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Schema-GraphQL
no_index:
  directory:
    - t
    - inc
requires:
  Cwd: '0'
  GraphQL::Schema: '0'
  Mojo::Base: '0'
  Mojo::Util: '0'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/lucas1/Mojolicious-Plugin-Schema-GraphQL/issues
  homepage: https://github.com/lucas1/Mojolicious-Plugin-Schema-GraphQL
  repository: https://github.com/lucas1/Mojolicious-Plugin-Schema-GraphQL
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
